### ISSUE TITLE
Integrate Graticule plugin for grid drawing

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#36]
Hmm, something still seems wrong-- when you zoom in and out, the boxes move around -- do you know why? We should open a new issue for this, since if they're being calculated based on actual latitude/longitude, they should be fixed!

https://publiclab.github.io/leaflet-blurred-location/examples/

**Comment by mridulnagpal** [comment]
I didn't get your point, as when we zoom in/out the boxes have to fit differently. For instance if the precision is one, a box will be having width of 0.1 degree as it is zoomed in it covers 0.01 degrees thus boxes will have different places, only one single line will be the same.

**Comment by jywarren** [comment]
Sorry, i meant that the same boxes seem to be moving at different zoom
levels -- try it out. And also, smaller boxes should "fit" into bigger
boxes, so some lines should stay the same -- like 100 `0.01` boxes would
fit exactly into one `0.1` box, right? And i'm not sure I see this
happening.

**Comment by mridulnagpal** [comment]
So what do you suggest we do?

**Comment by jywarren** [comment]
Well, I think we need to debug -- find out why they're not at fixed locations. Are you sure you're drawing them from a known starting point, or are they being drawn perhaps on a 0.1 grid, but just starting with wherever the upper left corner happens to be?

If we get too stuck, we could consider using the Graticule plugin, but let's see if we can take a careful look at the code and figure out why this is happening.

**Comment by jywarren** [comment]
Yes, look - the origin is being calculated from the map viewport: https://github.com/publiclab/leaflet-blurred-location/blob/master/src/core/gridSystem.js#L109

This needs to be locked to the nearest point on the actual latitdue/longitude grid -- but you can truncate that value using our truncation function to achieve this, no?

**Comment by mridulnagpal** [comment]
Perfect, I set the origin as constant and put up a PR, please have a look

**Comment by jywarren** [comment]
Cool, would you mind force pushing to your `gh-pages` branch so I can try
it out as a demo?

**Comment by mridulnagpal** [comment]
Yeah I did that, also here are two snaps of the same
![screenshot from 2017-06-23 02-11-59](https://user-images.githubusercontent.com/22350740/27455542-45cc588a-57bb-11e7-9f34-b266d7f66b6a.png)
![screenshot from 2017-06-23 02-11-44](https://user-images.githubusercontent.com/22350740/27455545-47f8a30c-57bb-11e7-884d-dad35aca0d1a.png)

**Comment by mridulnagpal** [comment]
@jywarren What do you say?

**Comment by jywarren** [comment]
Hm, i don't see anything at https://mridulnagpal.github.io/leaflet-blurred-location/examples/ -- can you try again? The screenshots look good but I want to be sure.

**Comment by mridulnagpal** [comment]
The page will show the master branch, won't it? Whereas the PR is from a different branch

**Comment by jywarren** [comment]
ah, but from your local machine, you can force merge your changes into your local `gh-pages` branch and then force push them up with `git push origin gh-pages` or `git push https://github.com/mridulnagpal/leaflet-blurred-location.git gh-pages`, and then we can see your work live over there. No need for a PR for that, it's just a temporary thing to show off what you're doing in this PR.

**Comment by mridulnagpal** [comment]
It seems there isn't a gh-pages branch in my repo so pushed to upstream/gh-pages, please have a look, till then I will create the gh-pages branch in my repo as well.
https://publiclab.github.io/leaflet-blurred-location/examples/

**Comment by jywarren** [comment]
oh ok -- but in the future please leave the main repo's gh-pages branch
as-is, since that's supposed to be the publicly accessible demo, and if
people (in theory) come across the project that's the demo they'll be
looking at.

Hmm, that one's still moving the origin around... maybe the push wasn't
successful?

**Comment by mridulnagpal** [comment]
I'll have a look

**Comment by mridulnagpal** [comment]
I made a branch named gh-pages in my repo as well and pushed the changes but there seems to be some issue, can you please have a look
https://mridulnagpal.github.io/leaflet-blurred-location/examples/

**Comment by jywarren** [comment]
I think you have to also add your `node_modules/leaflet`
and `node_modules/jquery` folders -- **only** to `gh-pages` -- because
those are required to run. `gh-pages` branch can get a little messy - just
don't let that messiness get back into your feature branches or master
branch!  :-)

**Comment by mridulnagpal** [comment]
I added the folders, still the same result

**Comment by mridulnagpal** [comment]
@jywarren Evenn after adding the folders I get the same thing please have a look

**Comment by jywarren** [comment]
I believe there's a building issue with github pages and I opened a pull request to merge in a holding file to solve it -- https://github.com/mridulnagpal/leaflet-blurred-location/pull/3

**Comment by jywarren** [comment]
awesome, that worked! https://mridulnagpal.github.io/leaflet-blurred-location/examples/

But your new origin code from https://github.com/publiclab/leaflet-blurred-location/pull/37 doesn't seem to be running there? or at least when i zoom in and out, the grid squares are still drawn from the upper right corner.

**Comment by jywarren** [comment]
Also https://github.com/publiclab/leaflet-blurred-location/pull/37 is now a bit out of date, and I tried rebasing it but haven't gotten very far. Can you rebase it and then push it both to the PR and to `mridulnagpal#gh-pages` again? Then we'll be testing out the latest version in the demo.

**Comment by mridulnagpal** [comment]
Done, please review the demo online https://mridulnagpal.github.io/leaflet-blurred-location/examples/

**Comment by jywarren** [comment]
OK, great, the demo is operating, but I still see that the grid lines are shifting back and forth. I'm not sure what the issue is -- 

```js
this._origin = this._map.project(L.latLng(0, 0));
```

Maybe you should choose the lat/lon of the upper right corner of the viewport -- using `getBounds()` -- http://leafletjs.com/reference-1.0.3.html#map-getbounds

**Comment by jywarren** [comment]
And compare to https://leaflet.github.io/Leaflet.Graticule/example/ -- and really, if we get stuck on this entirely, I think we may want to integrate https://github.com/leaflet/Leaflet.Graticule/ in, and simply use that -- it's great to have modular code to work on top of, and perhaps users of that project would like this extension of its use...

**Comment by mridulnagpal** [comment]
They will change when the precision is changed, please try being on the same precision as I have sent the snaps. As when the precision changes, the lines won't be the same. The area where there had been 10 lines now there would be 2 as we zoom out.

**Comment by jywarren** [comment]
They should change, but the smaller squares should fit perfectly into the
larger ones. For example where there is a square at 41-42 latitude, and
88-89 longitude, when we zoom in there should be squares at:

41.0, 41.1, 41.2, ... 41.9, 42.0

and:

88.0, 88.1, 88.2 ... 88.9, 89.0

See how this works in the Graticule demo. But in the demo you've posted,
the lines don't seem to either fit into each other or to stay consistent
when you zoom out... are you following the system I just described?

**Comment by mridulnagpal** [comment]
I think the cell sizes are the reason, for instance for 1 degree number of pixels is 32 for 0.1 degree  its 324 so the 10 boxes won't fit. Thus I am  adding a method to improve this

**Comment by jywarren** [comment]
Great. I'm sure you'll figure it out!

On Jun 26, 2017 5:58 PM, "Mridul Nagpal" <notifications@github.com> wrote:

I think the cell sizes are the reason, for instance for 1 degree number of
pixels is 32 for 0.1 degree its 324 so the 10 boxes won't fit. Thus I am
adding a method to improve this

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/leaflet-blurred-location/issues/36#issuecomment-311194068>,
or mute the thread

**Comment by mridulnagpal** [comment]
Added a helper method which calculated cell size for 1 degree then divides it by the precision we need. For example 1 degree has 1234 pixels and precision is 2 then cell size will be 12.34 rather than 12 which was the case before

**Comment by jywarren** [comment]
Ok, i closed out the PR in #37, but I'm changing the name of this one to request integrating the Graticule plugin for the grid drawing

This will be inside of [the GridSystem class](https://github.com/publiclab/leaflet-blurred-location/blob/master/src/core/gridSystem.js), so we'll still be customizing it a lot, for example to add `highlightCenterCell()` and such.

**Comment by mridulnagpal** [comment]
Roger that!

**Comment by mridulnagpal** [comment]
Let's get on with this as well, I was looking at the Plugin, but couldn't find how to install it and add it to the project.

**Comment by jywarren** [comment]
I think best look at the code of the demo. Great!

**Comment by mridulnagpal** [comment]
Is this done?

**Comment by jywarren** [comment]
Yep!
